# Generated by Django 3.2.6 on 2021-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
