# Generated by Django 3.2.6 on 2021-08-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210826_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='productmen',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productwomen',
        ),
        migrations.DeleteModel(
            name='Productmen',
        ),
        migrations.DeleteModel(
            name='Productwomen',
        ),
    ]
