# Generated by Django 3.2.6 on 2021-09-06 15:23

from django.db import migrations, models
import django.db.models.deletion
from mirage.tools import Migrator


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210828_1105'),
    ]

    migrations.RunPython(Migrator("dashboard", "Payment", "cname").encrypt,
                         reverse_code=Migrator("dashboard", 'Payment', 'cname').decrypt),
    migrations.RunPython(Migrator("dashboard", "Payment", "cardNum").encrypt,
                         reverse_code=Migrator("dashboard", 'Payment', 'cardNum').decrypt),
    migrations.RunPython(Migrator("dashboard", "Payment", "cvv").encrypt,
                         reverse_code=Migrator("dashboard", 'Payment', 'cvv').decrypt),
    migrations.RunPython(Migrator("dashboard", "Payment", "exd").encrypt,
                         reverse_code=Migrator("dashboard", 'Payment', 'exd').decrypt),

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200, null=True)),
                ('cardNum', models.CharField(max_length=200, null=True)),
                ('cvv', models.CharField(max_length=200, null=True)),
                ('exd', models.CharField(max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.order')),
            ],
        ),
    ]
